version: '3.8'

services:
  db:
    image: mariadb:10.3
    container_name: beehiveData
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - beehive_web

  backend:
    build: ./backend
    container_name: beehiveBackend
    restart: always
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}  
      - DB_NAME=${DB_NAME}
    networks:
      - beehive_web

  frontend:
    build: ./frontend
    container_name: beehiveFrontend
    restart: always
    ports:
      - "5000:5173"
    depends_on:
      - backend
    networks:
      - beehive_web      

networks:
 beehive_web:
    driver: bridge